version: "2"
services:
  nodeserver:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    ports:
      - "10069:3000"
    command: "npm start"

volumes:
  db_volume:
    external: true