version: "2"
services:
  nodeserver:
    container_name: dpanzoli_node
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./node3:/home/node/app
#     - ./node4:/home/node/app
    ports:
      - "10042:3000"
    command: "npm start"
  mongodb:
    container_name: dpanzoli_mongodb
    image: "mongo:4.0"
    volumes:
      - db_volume:/data/db

volumes:
  db_volume:
    external: true
